name: Default Workflow
on:
  pull_request:
  push:
      branches:
          - main
jobs:
  build:
    strategy:
      matrix:
        arch: ['x86_64']
        flavor: ['green']
    runs-on: ubuntu-latest
    steps:
      - name: Release space from worker
        if: always()
        run: |
          du -hcs /var/lib/snapd/snaps/* 
          # from https://github.com/apache/flink/blob/master/tools/azure-pipelines/free_disk_space.sh
          df -h
          sudo apt-get remove -y '^dotnet-.*' || true
          sudo apt-get remove -y '^llvm-.*' || true
          sudo apt-get remove -y 'php.*' || true
          sudo apt-get remove -y '^mongodb-.*' || true
          sudo apt-get remove -y '^mysql-.*' || true
          sudo apt-get remove -y '^temurin-.*' || true
          sudo apt-get remove -y azure-cli google-cloud-sdk microsoft-edge-stable google-chrome-stable firefox powershell mono-devel libgl1-mesa-dri || true
          sudo apt-get autoremove -y
          sudo apt-get clean
          # https://github.com/actions/virtual-environments/issues/2840
          sudo rm -rf /usr/local/lib/android # will release about 10 GB if you don't need Android
          sudo rm -rf /usr/share/dotnet # will release about 20GB if you don't need .NET
          sudo rm -rf /opt/ghc # removes haskell
          sudo rm -rf "$AGENT_TOOLSDIRECTORY" # removes all pre-cached tools (node, go, python, ruby) to free around 6Gb
          sudo rm -rf /usr/local/graalvm/
          sudo rm -rf /usr/local/.ghcup/
          sudo rm -rf /usr/local/share/powershell
          sudo rm -rf /usr/local/share/chromium
          sudo rm -rf /usr/local/lib/node_modules
          df -h
      - uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v3
        with:
            go-version-file: tests/go.mod
      - run: |
          git fetch --prune --unshallow
      - name: Install QEMU
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends qemu-system-x86 qemu-utils packer ovmf
      - name: Build
        run: |
          sudo -E make FLAVOR=${{matrix.flavor}} ARCH=${{matrix.arch}} build-example-iso
          sudo -E make FLAVOR=${{matrix.flavor}} ARCH=${{matrix.arch}} packer
      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: build-${{matrix.flavor}}-${{matrix.arch}}
          path: build
          if-no-files-found: error
