name: Default Workflow
on:
  pull_request:
  push:
      branches:
          - main
jobs:
  build:
    strategy:
      matrix:
        arch: ['x86_64']
        flavor: ['green']
    runs-on: ubuntu-latest
    steps:
      - name: Install Virtualization
        run: |
          sudo apt-get update
          sudo apt-get install -y ovmf qemu-system-arm qemu-efi-aarch64 qemu-system qemu-efi
      - name: Install Packer
        uses: hashicorp-contrib/setup-packer@v2
      - uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v3
        with:
            go-version-file: tests/go.mod
      - run: |
          git fetch --prune --unshallow
      - name: Build
        run: |
          make FLAVOR=${{matrix.flavor}} ARCH=${{matrix.arch}} build-example-iso
          make FLAVOR=${{matrix.flavor}} ARCH=${{matrix.arch}} PACKER_FIRMWARE=/usr/share/ovmf/OVMF.fd PACKER_ACCELERATOR=none PACKER_CPU=max packer
      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: build-${{matrix.flavor}}-${{matrix.arch}}
          path: build
          if-no-files-found: error
