name: Default Workflow
on:
  pull_request:
  push:
      branches:
          - main
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        arch: ['x86_64', 'arm64']
        flavor: ['green']
        media: ['iso', 'image']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: git fetch --prune --unshallow
      - name: Install Virtualization
        run: |
          sudo apt-get update
          sudo apt-get install -y ovmf qemu-system-arm qemu-efi-aarch64 qemu-system qemu-efi
      - name: Setup Docker QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build
        run: |
          sudo -E make FLAVOR=${{matrix.flavor}} ARCH=${{matrix.arch}} build-${{matrix.media}}
      - name: Install Go
        uses: actions/setup-go@v3
        with:
            go-version-file: tests/go.mod
      - name: Run tests
        run: |
          sudo -E make FLAVOR=${{matrix.flavor}} ARCH=${{matrix.arch}} ELMNTL_ACCEL=none ELMNTL_FIRMWARE=/usr/share/ovmf/OVMF.fd test-${{matrix.media}}
      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: build-${{matrix.flavor}}-${{matrix.arch}}
          path: build
          if-no-files-found: error
