name: PR

on:
 pull_request:
   paths:
     - conf/**
     - toolkit/**
     - tests/**
     - make/**
     - .github/**
     - Makefile
     - tests/**

jobs:
  build-matrix:
    strategy:
      matrix:
        arch: ['x86_64']
        flavor: ['green']
    uses: ./.github/workflows/build_and_test.yaml
    with:
      arch: ${{ matrix.arch }}
      flavor: ${{ matrix.flavor }}
